### ISSUE TITLE
Incorrect behavior of `ToggleScratchpad` with focus behavior `ClickTo`

### ISSUE THREAD

**Issue by SamClercky** [leftwm/leftwm#856] opened 2022-09-24 22:20 UTC
### Describe the bug

This is a follow up of PR #768 where if the manual handling of the visibility in the scratchpad commands is not handled in the commands itself, the behavior is not as expected when focus behavior is set to `ClickTo`.

Observed behavior: (more in information in detail can be found in previously mentioned PR)
* Toggling SP on only works when there is a window that has focus
* Toggling SP off doesn't return focus to any other visible window
* `NextScratchPad` / `PrevScratchPad` first toggle the curren SP window of only with the next execution they open the next SP window

### Expected behavior (optional)

* `ToggleScratchPad` should toggle the scratchpad more than once without the handling of the visibility in the scratchpad commands.
* Toggling the scratchpad should return focus to another visible window
* `NextScratchPad` / `PrevScratchPad` should not toggle the current scratchpad and only cycle when there is a scratchpad visible + cycle immediatly

### Steps to reproduce (optional)

1. `git revert d598cbc`
2. Make sure that `focus_behavior` is set to `ClickTo`
3. Go to a tag with no open windows
4. Toggle twice the scratchpad with `ToggleScratchPad` (show + hide)
5. Try to toggle again -> nothing happens

Minimal config:
```rust
    focus_behavior: ClickTo,
    scratchpad: [
        (name: "ScratchpadTerminal", value: "alacritty", x: 0.055, y: 65, width: 0.89, height: 0.34),
        (name: "BTop", value: "alacritty -e btop", x: 10, y: 65),
        (name: "DynamicScratchpad", value: ""),
    ],
    keybind: [
        (command: ReleaseScratchPad, value: "", modifier: ["modkey", "Shift"], key: "d"),
        (command: AttachScratchPad, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "d"),
        (command: NextScratchPadWindow, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "comma"),
        (command: PrevScratchPadWindow, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "period"),

        (command: ReleaseScratchPad, value: "", modifier: ["modkey", "Shift"], key: "d"),
        (command: AttachScratchPad, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "d"),
        (command: NextScratchPadWindow, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "comma"),
        (command: PrevScratchPadWindow, value: "DynamicScratchpad", modifier: ["modkey", "Control"], key: "period"),
    ],
```

### OS / Distro

Linux manjaro-btw 5.15.65-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:47 UTC 2022 x86_64 GNU/Linux

### Additional System Information (optional)

```text
LeftWM has been build from `git` during PR #768.
```

### LeftWM Check

```text
:: LeftWM version: 0.3.0
:: LeftWM git hash: e3a1454
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
```

**Comment by VuiMuich** [comment] 2023-11-15 06:53
I currently can't reproduce any of the reported issues, so I close this as solved. Please reopen if anything is still missing.

**Closed by VuiMuich** 2023-11-15 06:53 UTC
Labels: bug
