### ISSUE TITLE
ScratchPad does not follow rules

### ISSUE THREAD

**Issue by MrMic** [leftwm/leftwm#720] opened 2022-02-27 18:24 UTC
**Describe the bug**
When I trigger the ScatchPad, it opens as if it was not a scratchpad but 
a normal window.
- When I trigger the keybinding again, It should disappear, and NO ... => Another 
- window is open  :/

**To Reproduce**
[scratchpad]]
name = "Alacritty"
value = "terminator"
x = 0.20
y = 0.20
height = 0.80
width =  0.54

[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty" # Name set for the scratchpad
modifier = ["modkey"]
key = "s"

**Expected behavior**
SCrtchPad should appear and disappear.

**Environment:**
 - OS/Distro: Ubuntu 20.04

leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: 9ad1dfd
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
ERROR: `commands.pipe` is deprecated. See https://github.com/leftwm/leftwm/issues/652 for workaround.

**Comment by VuiMuich** [comment] 2022-02-28 13:29
I guess the missing `[` in `[[scratchpad]]` is just a copy-pasta in creating this post, right?

Which theme are you using?

Can you please post you complete config (ideally using code block formatting)?

**Comment by MrMic** [comment] 2022-02-28 22:01
Yes, the " [ " missing is just just a Paste mistake ...
- I use Polybar provided by the LeftWM Window Manger .

- Here is my config:

`
modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["", "", "", "", "","", "", "", "" ]

layouts = ["Monocle", "MainAndVertStack", "MainAndDeck"]
layout_mode = "Workspace"

disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

window_rules = [
    {window_class = "vivaldi", spawn_on_tag = 4},
    {window_class = "ulauncher", spawn_floating = true},
    {window_class = "jetbrains-studio", spawn_on_tag = 9, spawn_floating = true},
]

[[scratchpad]]
name = "Alacritty"
value = "terminator"
x = 0.20
y = 0.20
height = 0.80
width =  0.54

[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty" # Name set for the scratchpad
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "ToggleFloating"
modifier = ["modkey", "Control"]
key = "f"	

[[keybind]]
command = "Execute"
value = "amixer set Master 5%- unmute"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "amixer set Master 5%+ unmute"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute 1 toggle"
modifier = []
key = "XF86XK_AudioMute"


[[keybind]]
command = "Execute"
value = "rofi -combi-modi window,drun,ssh -theme solarized -font 'hack 10' -show combi -icon-theme 'Papirus' -show-icons"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "xscreensaver-command -lock"
modifier = ["modkey", "Control"]
key = "s"

[[keybind]]
command = "Execute"
value = "terminator"
modifier = ["modkey", "Control"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "c"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["Control"]
key = "Tab"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"


[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "underscore"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"


[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "minus"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "underscore"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "ccedilla"

`

**Comment by VuiMuich** [comment] 2022-03-01 05:43
🤔 the config looks alright, my suspicion of the one `toml` issue we don't catch with `leftwm check` does not appear. 

Is it possible, that for some odd reason `Super+s` also is a keybind in `terminator`?
Have you tried a different keybind or terminal emulator?

Btw. you don't have to name your scratchpad `Alacritty`, it really can be any name. Or did you try to keep it as close to the wiki config as possible to track the bug down?

**Comment by MrMic** [comment] 2022-03-01 08:38
- No the keybind is not caught elsewhere. I change it and got the same result: a new terminal is spawned instead of toggling.
- For the name, I, indeed, want to stick to the given example. I just want to try the ScratchPad ...
- BTW: spawn_on_tag and spawn_floating do not work either...

**Comment by VuiMuich** [comment] 2022-03-01 11:51
This is odd.

For reference, this is my scratchpad setup:
```toml
scratchpad = [
  {name = "ScratchpadTerminal", value = "alacritty", x = 0.055, y = 65, width = 0.89, height = 0.34},
  {name = "BTop", value = "alacritty -e btop"},
]

keybind = [

# value is name set for the scratchpad 
{ command = "ToggleScratchPad", value = "ScratchpadTerminal", modifier = ["modkey"], key = "s" },
{ command = "ToggleScratchPad", value = "BTop", modifier = ["modkey"], key = "t" },

# rest of keybinds omitted
]
```

**Comment by MrMic** [comment] 2022-03-01 12:09
Just try ur config, and still not working 😥
I will unfortunately stick to XMonad for the moment.
And one more drawback: when I change layout, it changes it 
for all the tags ...

**Comment by VuiMuich** [comment] 2022-03-01 16:37
> Just try ur config, and still not working 😥 I will unfortunately stick to XMonad for the moment. 

I am sorry we couldn't figure it out, what caused the issue. Thanks though for your efforts. If by any chance you happen to find a solution or the cause of this bug some feedback would be much appreciated.

> And one more drawback: when I change layout, it changes it for all the tags ...

For this there is the config option ̀ layout_mode` with ̀ workspace` or `tag` as options.

**Comment by MrMic** [comment] 2022-03-01 17:12
The "layout_mode" configuration option works jst fine: thanks.
Read the docs a few days ago, and indeed it was written there: my bad.

- "spawn_on_tag" and "spawn_floating" is not working too as expected ...
- I will read the Docs again, maybe I missed something ...

Anyway, thanks for your time.
Rgds,
Michaël C.

**Comment by Miusaky** [comment] 2022-04-23 21:43
Having this issue as well. 

```
scratchpad = [
    { name = "Kitty", value = "kitty", x = 860, y = 390, height = 300, width = 200 },
]


[[keybind]]
command = "ToggleScratchPad"
value = "Kitty" 
modifier = ["modkey"]
key = "s"
```
[Full config](https://pastebin.com/FZyUsVmR). 

I tried the wiki config snippet as well which did not work either. Both configs spawn a new instance with each trigger.

Unrelated to this issue but window_rules and disable_tile_drag do not seem to work either with the above config. Did I misunderstand the wiki? Leftwm-check does not produce an error.

**Comment by VuiMuich** [comment] 2022-04-25 18:29
> Having this issue as well.
> 
> ```
> scratchpad = [
>     { name = "Kitty", value = "kitty", x = 860, y = 390, height = 300, width = 200 },
> ]
> 
> 
> [[keybind]]
> command = "ToggleScratchPad"
> value = "Kitty" 
> modifier = ["modkey"]
> key = "s"
> ```
> 
> [Full config](https://pastebin.com/FZyUsVmR).
> 
> I tried the wiki config snippet as well which did not work either. Both configs spawn a new instance with each trigger.
> 
> Unrelated to this issue but window_rules and disable_tile_drag do not seem to work either with the above config. Did I misunderstand the wiki? Leftwm-check does not produce an error.

Looking at your full config I'd like to suggest to move the `layout_mode` after the `scratchpad` table.

**Comment by Miusaky** [comment] 2022-04-26 00:54
Switching from the Void Linux repo version to the Git build solved the scratchpad issue for me, so I don't know if moving `layout_mode`would solve the issue.

**Comment by mastern2k3** [comment] 2022-06-08 19:06
Experiencing this too :+1: 
Toggle scratchpad action just creates more scratchpads.

**Comment by mastern2k3** [comment] 2022-06-09 07:38
Hey @VuiMuich , I'm very interested in making this work.
What would be a good place to start?
Do you have any intuitions about what could be the problem?

**Comment by haukkagu** [comment] 2022-06-18 11:59
I'm experiencing the same issue (toggle scratchpad creates more scratchpads) in addition to numerous other bugs. I switched from the void repo version to the git build, and it resolved many of the other bugs, but the scratchpad issue persists.

Did you manage to get it working, @mastern2k3?

**Comment by mastern2k3** [comment] 2022-06-18 12:27
@haukkagu nope

**Comment by VuiMuich** [comment] 2022-06-22 07:16
Sorry for the delayed response. RL is very attention grabbing these days...

It's really hard to say, where the exact issue sits.

@mastern2k3 which version are you on?

**Comment by mike-lloyd03** [comment] 2022-09-26 05:16
I just started having this issue with Leftwm 0.3.0, Git-Hash: cdc9157 but it only occurs when using `config.ron` and not with my `config.toml` file.

config.ron
```rust
    scratchpad: [
        (
            name: "Alacritty",
            value: "WINIT_X11_SCALE_FACTOR=1 alacritty -t \"Alacritty - Scratch\" -o window.opacity=0.8 -e bash -c \"tmux a -t scratch || tmux \"new-session;\" rename-session scratch\"",
            x: 0.05,
            y: 35,
            height: 0.5,
            width: 0.9
        ),
    ],
```

config.toml
```toml
[[scratchpad]]
name = "Alacritty"
value = 'WINIT_X11_SCALE_FACTOR=1 alacritty -t "Alacritty - Scratch" -o window.opacity=0.8 -e bash -c "tmux a -t scratch || tmux \"new-session;\" rename-session scratch"'
x = 0.05
y = 35
height = 0.50
width =  0.9
```

**Comment by VuiMuich** [comment] 2022-09-26 05:35
Thanks for reporting this.
First I thought this might be related to #860, but it looks your Ron snippet looks ok, as far as my pre-coffee morning brain can tell. 

@SamClercky Any ideas?

**Comment by SamClercky** [comment] 2022-09-26 06:27
The scarthpad identifies its windows through their pid. In certain cases this can be an issue as for example VSCode (code command) first creates a new window (new pid) and then kills itself (original pid)

I never personally used termite, but this might be giving the issue I first thought. Then I saw that other configs with kitty and alacrity were failing too, so I am unsure on that front.

For the issue between RON and TOMl, the value in RON probably misses some `\` around `\"new-session\"`.

Hope this helps :smile:

**Comment by mike-lloyd03** [comment] 2022-09-26 18:53
Ah you're right. I forgot to double escape the quotes inside the `bash -c` command. This works:

```rust
    scratchpad: [
        (
            name: "Alacritty",
            value: "WINIT_X11_SCALE_FACTOR=1 alacritty -t \"Alacritty - Scratch\" -o window.opacity=0.8 -e bash -c \"tmux a -t scratch || tmux \\\"new-session;\\\" rename-session scratch\"",
            x: 0.05,
            y: 35,
            height: 0.5,
            width: 0.9
        ),
    ],
```

**Comment by VuiMuich** [comment] 2022-09-27 09:51
Also can't reproduce the original issue on `7e7b6c4`, so closing this.
If there is anything unsolved that I missed, please feel free to reopen.

**Closed by VuiMuich** 2022-09-27 09:51 UTC
Labels: bug
