### ISSUE TITLE
Unexpected behaviour when switching tags with multiple monitor

### ISSUE THREAD

**Issue by jwnpoh** [leftwm/leftwm#297] opened 2021-04-19 01:10 UTC
Hello, I've recently encountered unexpected behaviour where LeftWM randomly switches focus tto another monitor/workspace by itself. Here's the scenario:

I have monitor 2 running some process on Tag 9.

I'm working on monitor 1 on Tag 1. I need to find something that I forgot which tag it's on, so I cycle through the tags one at a time - Tag 2, Tag 3, etc. Somewhere along the way, randomly, say for example when I switch to Tag 5, LeftWM changes the tag on monitor 2 and Tag 5 gets diplayed on monitor 2. Interestingly the mouse cursor (which I arbitrarily use to find where my focus is when I lose focus) remains on monitor 1 when this happens.

Any advice if I'm doing something wrong here? Thanks!

Edit: I think this might be related to #275 somehow. When this behaviour happens my polybar seems to display similarly erroneous output, except that I don't necessarily have Brave or Firefox open on those affected tags.

**Comment by VuiMuich** [comment] 2021-04-19 06:02
Hi there

let me ask you a few things:
first of all, which version of leftwm are you using? Git or packaged? `leftwm-state -h` should print you `0.2.8` for the most recent git-version and `0.2.7` for the latest packaged version. If you have anything older please consider updating.

> I'm working on monitor 1 on Tag 1. I need to find something that I forgot which tag it's on, so I cycle through the tags one at a time - Tag 2, Tag 3, etc. Somewhere along the way, randomly, say for example when I switch to Tag 5, LeftWM changes the tag on monitor 2 and Tag 5 gets diplayed on monitor 2. Interestingly the mouse cursor (which I arbitrarily use to find where my focus is when I lose focus) remains on monitor 1 when this happens.

This sounds like the workspaces are just swapping tags as expected: When you have tag 3 on workspace 1 and tag 5 on workspace 2 and you focus is on workspace 2 as you start switching tags. As you switch to tag 3 on workspace 2 leftwm will swap tag 5 to workspace 1.
This might feel a bit random in the beginning if you are new to leftwm, especially if you are coming from awesomewm, i3, dwm, bspwm etc. as their default is that each 'screen' has its own set of 'workspaces'. This swapping behaviour has leftwm in common with at least xmonad and qutile.

Can you try to find the actual pattern, when the focus moves or stays? Can you observe this with any layout and number of windows? We previously had some issues to get proper focus when the mousepointer sits on "empty space".

> Edit: I think this might be related to #275 somehow. When this behaviour happens my polybar seems to display similarly erroneous output, except that I don't necessarily have Brave or Firefox open on those affected tags.

Could this be related to #295 instead?
If not, do you have heavy systemload in these situations? I experienced a glitch yesterday, probably related to heavy load, as I was installing system updates and at the same time closing qutebrowser freed a view Gigs of swap and ram.

**Comment by jwnpoh** [comment] 2021-04-20 13:39
Thanks for responding. 

> This sounds like the workspaces are just swapping tags as expected: When you have tag 3 on workspace 1 and tag 5 on workspace 2 and you focus is on workspace 2 as you start switching tags. As you switch to tag 3 on workspace 2 leftwm will swap tag 5 to workspace 1.

I am aware of this behaviour and you are right, it did take awhile to get used to coming from i3 but this wasn't it. I made sure to check that I hadn't accidentally swapped active tags on either screen.

Apologies for the noobery here, both in terms of Rust literacy and how PRs work. I tried reading through #295 and I don't really understand what is going on, but it seems like that's an active branch of development with some recent commits that have been merged with master; would that mean that a recent update would have changed some? I ask this because I was off my computer the whole of yesterday, and as I tried today to replicate the expected behaviour I reported earlier, I was unable to reproduce the issue. Everything seems to be working fine and dandy now.

Should I close this issue now?

**Comment by VuiMuich** [comment] 2021-04-20 18:31
Oh right, now that you mention it I remember that I put 'semi-code' in the description of the PR.
If I had put it in clear words it would've benn something like this:

When using the "move window commands" on a single window in on a tag leftwm crashes. 

So yes, if you live on a got-based install and updated yesterday and can't reproduce the mal behavior it was probably related to the aforementioned PR.
Is the seemingly random focus behavior not reproducible anymore as well, then you might indeed close this issue.

**Comment by jwnpoh** [comment] 2021-04-28 08:26
Hi, I'm reopening this issue because the weird behaviour suddenly resurfaced. I made a [quick screen recording](https://youtu.be/VvWxM3y_RQg) which hopefully sufficiently demonstrates this behaviour.

- Note that I set my screen 2 to Tag 9 and change focus to screen 1, which is on Tag 1. 
- As I try to change tags from Tag 1 to Tag 2, the focus unexpectedly switches over to screen 2. I notice this and manually switch focus back to screen 1. 
- On screen 1, I switch from Tag 2 to Tag 3 with no problems, but when I attempt to change to Tag 4, now Tag 4 unexpectedly appears on screen 2 instead.
- I try again, this time the focus and tag switch agan unexpectedly jumps to screen 2 when changing Tag 6 to Tag 7.

I've tried this a couple other times and it does not seem unique to Tags 4 and 7, but happens quite randomly regardless of tag number - I can't find any other meaningful pattern to this behaviour.

This is the output of `leftwm-state -h`:

```
$ leftwm-state -h
LeftWM State 0.2.8
```

**Comment by jwnpoh** [comment] 2021-04-28 08:50
I think can confirm, it's the "empty space" issue. See this [second screen recording](https://youtu.be/VGI9c7ZvSw4).

This is not by design, right?

Thanks for having a look at this!

**Comment by AethanFoot** [comment] 2021-04-28 11:25
I believe this is happening as focus moves to the closest window, however there isnt a check to see whether the closest window is on that workspace. Another way this issue shows is if you close all the windows on one worksapce, and spam the keybind, windows on the other workspace will start closing. Ill look at this now, but will wait until lex is finished testing the clean up pull request as I suspect Ill create merge errors.

**Closed** 2021-05-03 12:38 UTC
