### ISSUE TITLE
Floating dialogues smaller than expected

### ISSUE THREAD

**Issue by tramhao** [leftwm/leftwm#574] opened 2021-11-11 04:11 UTC
**Describe the bug**
Floating dialogues popped up by programs are smaller than normal.

**To Reproduce**
1. start gimp and open any image.
2. Click on 'colors'->'desaturate'->'desaturate'
3. the floating dialogue is smaller and some options are hidden. It can be enlarged by mod+mouse right drag, but need to do it every time.

**Expected behavior**
The size of floating windows should have a sane default to display everything in the diagloue.

**Screenshots**

**Environment:**
 - OS/Distro:  arch
 - Output of `leftwm-check`
x leftwm-check
:: LeftWM version: 0.2.10
:: LeftWM git hash: 26cc711
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Additional context**
wrong dialogue
![pic-window-211111-1301-27](https://user-images.githubusercontent.com/7751505/141240372-51a0b955-ff3d-466c-8089-7c736f362e2f.jpg)

correct dialogue
![pic-window-211111-1301-50](https://user-images.githubusercontent.com/7751505/141240391-4c636d67-54d0-4a3e-9042-170962179545.jpg)

**Comment by VuiMuich** [comment] 2021-11-11 06:35
Is it possible for you to checkout if #571 fixes it for you?
If not, could you post the `xprop` info, please?

**Comment by tramhao** [comment] 2021-11-11 08:42
Thanks so much. I think #571 solved the problem I have. Now the dialogue is big enough to show all items inside it. Have a nice day.

**Comment by hertg** [comment] 2021-11-24 06:35
I still experience this issue in [DBeaver](https://dbeaver.io/) on all popup windows.
I guess because they don't specify a min-size?

**xprop of preferences window**
```
_NET_WM_DESKTOP(CARDINAL) = 7
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x5602a60
		bitmap id # of mask for icon: 0x5602a66
		window id # of group leader: 0x5600001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x36, 0x5e, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 100, 100
WM_TRANSIENT_FOR(WINDOW): window id # 0x560003f
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 90188372, 90188373
_NET_WM_USER_TIME(CARDINAL) = 842157
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5602a53
WM_CLIENT_LEADER(WINDOW): window id # 0x5600001
_NET_WM_PID(CARDINAL) = 17684
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "arch-desktop"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 0 by 0
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "DBeaver", "DBeaver"
WM_ICON_NAME(STRING) = "Preferences "
_NET_WM_ICON_NAME(UTF8_STRING) = "Preferences "
WM_NAME(STRING) = "Preferences "
_NET_WM_NAME(UTF8_STRING) = "Preferences "
```

**Comment by VuiMuich** [comment] 2021-11-24 07:20
Yea, I guess leftwm has not hints here, how to size this window correctly. Do you have another WM running, where you can gather `xwininfo` from the correct sized image, maybe there is a clue how other WMs determine the size correct.

**Comment by hertg** [comment] 2021-11-24 18:41
I started up dwm and the popup window is sized correctly there.
Maybe leftwm ignores some resize requests from the window itself or something? I'm still too unfamiliar with the X11 API.

<details>
  <summary>xprop</summary>
  
  ```
WM_STATE(WM_STATE):
        window state: Normal
        icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
        Client accepts input or input focus: True
        Initial state is Normal State.
        bitmap id # to use for icon: 0x1000e9e
        bitmap id # of mask for icon: 0x1000ea4
        window id # of group leader: 0x1000001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x36, 0x5e, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) =
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 635, 536
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000042
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16780946, 16780947
_NET_WM_USER_TIME(CARDINAL) = 44345344
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1000e91
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 142537
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "arch-desktop"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
        program specified location: 0, 0
        program specified minimum size: 0 by 0
        program specified base size: 0 by 0
        window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "DBeaver", "DBeaver"
WM_ICON_NAME(STRING) = "Preferences "
_NET_WM_ICON_NAME(UTF8_STRING) = "Preferences "
WM_NAME(STRING) = "Preferences "
_NET_WM_NAME(UTF8_STRING) = "Preferences "
  ```

</details>

<details>
  <summary>xwininfo</summary>
  
  ```
xwininfo: Window id: 0x1000e90 "Preferences "

  Absolute upper-left X:  2241
  Absolute upper-left Y:  374
  Relative upper-left X:  2241
  Relative upper-left Y:  374
  Width: 635
  Height: 536
  Depth: 24
  Visual: 0x515
  Visual Class: TrueColor
  Border width: 2
  Class: InputOutput
  Colormap: 0x1000002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +2241+374  -2240+374  -2240-526  +2241-526
  -geometry 635x536+2241+374
  ```
  
</details>

**Comment by AethanFoot** [comment] 2021-11-24 21:32
@hertg That is correct (I presume as the sizing looks too random to be a default fallback), we now ignore the configure request as that was placing the windows in the top left. For dialogs we could make it so we only ignore the positioning and take on the sizing (we may need to reposition the window though).

**Comment by VuiMuich** [comment] 2021-11-24 21:59
What about a function, say `sanitize_window_dimensions`, that chooses the most reasonable size.
Like in this case the `WM_SIZE_HINTS` are not helpful, so we use the configure request, but it is a floating child-window, so we want to define the position, by gravity relevant to its parent.
In other cases we need to sort the different hints to be useful etc.

Just dropping some random thoughts after a long day, so this might as well be a bogus idea...

**Comment by AethanFoot** [comment] 2021-11-25 14:05
Does #587 fix this with correct centering?

**Comment by hertg** [comment] 2021-11-25 15:12
> Does #587 fix this with correct centering?

I'm running commit f86842a 
It doesn't fix the issue I have in DBeaver unfortunately.

To reproduce
1. Install the `dbeaver` package (`pacman -S dbeaver`)
1. Start dbeaver
1. In the toolbar, click on `Window` > `Preferences`
1. The preferences window will open in `100x100`
    ![image](https://user-images.githubusercontent.com/3533648/143465641-0b93d964-e0dc-4a2b-b3be-c915acaec643.png)

**Comment by AethanFoot** [comment] 2021-11-25 16:53
Ok I have figured out why we are having issues with these windows.
1. For some reason this window has a type of normal when it is clearly a dialog.
2. Again for some reason they tell us to configure the window before they have actually mapped the window.
:face_exhaling:

**Comment by AethanFoot** [comment] 2021-11-25 18:29
@hertg I have it now to where the configure request is used, by using the window attributes to get the windows setting before being mapped. This means we use the request sent by the app, however they seem to send a good request (good looking sizes) but it then sends another with smaller sizes for some reason. We may want to address the default sizing in another pr, should we make a new issue to track this (or is there one already one?).

**Comment by hertg** [comment] 2021-11-25 19:25
@AethanFoot That's weird. I checked out your latest commits and now it opens at `198x198`, i guess these are those smaller sizes you mentioned?

This problem with dbeaver is not a big issue for me, it's the only application where I currently have this problem. I'm not exactly sure what you mean by addressing the default sizing?

**Comment by AethanFoot** [comment] 2021-11-25 19:30
@hertg Ye they initially send something like (7 hundred something)x(5 hundred something) then the 200x200 (198x198 without the borders)

**Comment by VuiMuich** [comment] 2021-11-25 21:17
As a dirty hack, if we assume the 'bigger' window sizes are always the 'saner ones'?

**Comment by hertg** [comment] 2021-11-25 22:17
Hmmm, no idea how we should handle this. I wonder what dwm did with this, because it seems to work alright there.
To be fair though, dwm does have some issues with popups too (when having multiple intellij instances for example, in leftwm we actually addressed the intellij/popup issue).

@AethanFoot I guess i'm a bit out of the loop on that one, because I still don't understand what you mean exactly :laughing: I wasn't sure if you meant closing this issue here, because IMO this is still open. I guess the behavior of dbeaver issuing two configure requests is weird. It does seem to me like there could be something off with LeftWM though, because otherwise this would also be a problem in other WMs?

**Comment by TornaxO7** [comment] 2022-09-26 21:07
Hm... I don't have any issues on my machine. @hertg should we close this issue for now?

**Comment by hertg** [comment] 2022-09-26 21:09
I still have this issue in [dbeaver](https://dbeaver.io/)

**Comment by VuiMuich** [comment] 2022-09-27 09:34
`dbeaver` comes with this hint:
```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 0 by 0
		program specified base size: 0 by 0
		window gravity: NorthWest
```
I thought, we already had implemented to set some sane defaults for the 0x0 size :monocle_face:

**Comment by hertg** [comment] 2022-10-06 21:08
Created a follow up issue at [#880](https://github.com/leftwm/leftwm/issues/880)

**Closed by hertg** 2022-10-06 21:08 UTC
Labels: bug
