### ISSUE TITLE
leftwm-worker crashing when `focus-window-down`

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#328] opened 2021-05-10 06:59 UTC
I experienced a few crashes during the past week and I am not fully sure for the reason. It might even be different reasons. 
Some occurred after moving a window to a tag and switch to the tag right after. In this cases the moved window was unable to catch focus. Sometimes toggling full-screen on and off cures this, sometimes worker crashes into a hard reload with reason 'Any' reported in journalctl. 
Some other time the crash happened on a tag with a single `quzebtowser` window. This time it froze the worker so bad it didn't respond to keybinds (quetebrowser was still working fine though) not even respond to a `leftwm-state -q` from the `tty` and I had to `pkill` it from there. Therefore it didn't leave any trace in journalctl either.

To be fair I have merged a bunch of PRs to my local `HEAD`, but have to look them up, when home from work.

I know this is quite vague, but thought I open this as a tracking issue anyway, maybe somebody is experiencing similar crashes but is hesitant to report due to the uncertain reason.

**Comment by mautamu** [comment] 2021-05-10 07:14
Hmm I did have one while working on #323 if you've merged that one into your local branch. Thought it had been ironed out though, as I have it on my tree now and haven't had a crash since.

**Comment by VuiMuich** [comment] 2021-05-10 09:10
I am only sure of having #319 on my tree, possibly also `299`. Gonna look it up as soon as I am back on that machine.

**Comment by VuiMuich** [comment] 2021-05-10 15:49
It actually only is `319` beyond master what I did my last build against.

**Comment by VuiMuich** [comment] 2021-05-12 20:53
I think I found what used to make `worker` crash, yet it doesn't crash anymore but still results in a bug:
when on a tag with only a single window `FocusWindowDown` detaches (my guess is from `manager.windows`) the window and only a reload brings it back to the list of managed displays on tag `1`

**Comment by VuiMuich** [comment] 2021-05-18 06:14
Unfortunately it seems it is still persisting.
In addition to the `FocusWindowDown` relation I believe this only happens, when the tag holding the single window while focusing down held more then one windows at an earlier point of time.
I guess later this week I can have an actual look at the code.

**Comment by AethanFoot** [comment] 2021-05-18 11:42
For some reason I can't reproduce this issue, even when installing unclutter to see if it is behaving badly (which it wasn't). So I won't be able to help too much with this one.

**Comment by VuiMuich** [comment] 2021-05-18 13:02
Yea, `unclutter` definitely is unrelated, I installed it my self just yesterday. 

I'll triage this further and try to come up with clear steps to reproduce this.

**Comment by VuiMuich** [comment] 2021-05-19 06:03
It looks like this is a `monocle` bug:
- switch to `monocle` layout
- go to empty tag (other then `tag 1`)
- open terminal (or any other single window)
- `focus down`
- open another window
now the first window stays on top but can't get focus anymore and can't even be dragged by mouse to be floating. Only a `soft reload` gets this window back and inserts it to the first tag.

**Closed** 2021-06-08 19:02 UTC
