### ISSUE TITLE
Opera browser flickering when in full screen mode

### ISSUE THREAD

**Issue by n1s** [leftwm/leftwm#718] opened 2022-02-23 18:04 UTC
**Describe the bug**
Opera browser flickering black when in full screen mode. Youtube videos go black only when video paused. 

** Also - leftwm does not apply theme's border on opera's window for some reason 

**To Reproduce**
1. Open opera browser
2. Enter full screen mode
3. Do anything - browse, type etc.

**Expected behavior**
Firefox not affected only happening in opera.

**Screenshots**
Looks pretty light on my screencast but it can go crazy (https://webmshare.com/play/3KAD8)

**Environment:**
 - OS/Distro: Arch
 - Output of `leftwm-check`
```
:: LeftWM version: 0.3.0
:: LeftWM git hash: 9ad1dfd
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK


$ pacman -Qi opera     
Name            : opera
Version         : 84.0.4316.14-1
Description     : A fast and secure web browser
Architecture    : x86_64
URL             : https://www.opera.com/
Licenses        : custom:opera
Groups          : None
Provides        : None
Depends On      : gtk3  alsa-lib  libnotify  curl  nss  libcups  libxss  ttf-font  desktop-file-utils  shared-mime-info
                  hicolor-icon-theme
Optional Deps   : opera-ffmpeg-codecs: playback of proprietary video/audio [installed]
                  upower: opera battery save [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 236.78 MiB
Packager        : Ike Devolder <ike.devolder@gmail.com>
Build Date      : Thu 17 Feb 2022 07:31:59 CET
Install Date    : Tue 22 Feb 2022 20:59:39 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by hertg** [comment] 2022-09-04 11:47
I can't reproduce the flickering, might this be an X.org or driver issue?
As for the border not showing, I can reproduce that. But it probably is an issue with Opera, similar to how Chrome browsers didn't display the border when "Use system title bar and borders" was not enabled (it is disabled by default)).
Check if you find information on how to use system decorations with opera, there probably is an option somewhere, because it also seems to display the minimize/maximize/close buttons by default which you probably don't want in a tililng wm anyway.
![image](https://user-images.githubusercontent.com/3533648/188311755-16f01fdb-6d01-4085-813d-fca0d7bbe898.png)

Closing it for now, reopen if it can be reproduced and pinned on LeftWM.

**Closed by hertg** 2022-09-04 11:47 UTC
