### ISSUE TITLE
Firefox 86.0: Picture-in-Picture window should float

### ISSUE THREAD

**Issue by mautamu** [leftwm/leftwm#220] opened 2021-02-27 03:51 UTC
Howdy,

I have been experimenting with the new Picture-In-Picture mode on Firefox. LeftWM sizes the new PIP window as if it were a normal window, but it should instead allow for floating on said window.

Best,
Mautamu

**Comment by VuiMuich** [comment] 2021-02-27 13:36
Can confirm and also, when this normal window is put in floating manually, I has some black margins to fill the gap between video-aspect-ratio and window aspect-ratio. When resized the window keeps the window-aspect-ratio.

**Comment by carrascomj** [comment] 2021-03-08 17:34
Xmonad has the same behaviour so it is _probably_ on Firefox side (they did not attach the proper floating info into the spawned window).

**Comment by VuiMuich** [comment] 2021-11-25 20:45
Just for reference here is the `xprop` of a firefox PiP window (icon characters omitted):
```
_NET_WM_DESKTOP(CARDINAL) = 4
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x5e000ad
		bitmap id # of mask for icon: 0x5e000b3
		window id # of group leader: 0x5e00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
WM_WINDOW_ROLE(STRING) = "PictureInPicture"
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):

[omitted icon characters]

_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 98566315, 98566316
_NET_WM_USER_TIME(CARDINAL) = 50835164
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5e000aa
WM_CLIENT_LEADER(WINDOW): window id # 0x5e00001
_NET_WM_PID(CARDINAL) = 295708
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "manjobook"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 142 by 80
		program specified maximum size: 16384 by 16384
		program specified base size: 142 by 80
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Toolkit", "firefox"
WM_ICON_NAME(STRING) = "Picture-in-Picture"
_NET_WM_ICON_NAME(UTF8_STRING) = "Picture-in-Picture"
WM_NAME(STRING) = "Picture-in-Picture"
_NET_WM_NAME(UTF8_STRING) = "Picture-in-Picture"
```
I am with hertg, that the pip being a normal tiled window is not too wrong, and it is easy enough to toggle float on it..

Should we close this?

**Closed** 2021-11-25 20:59 UTC
Labels: bug

**Comment by hertg** [comment] 2021-11-25 22:01
Just something I noticed recently: The picture-in-picture window of Firefox is always on top of all other windows. Is that by design? I'm actually not complaining, it didn't ever bother me. :smile:

**Comment by VuiMuich** [comment] 2021-11-25 22:31
Just guessing, but it would be kind of intended by firefox this way and they might have pulled off something sneaky to enforce this behaviour?
