### ISSUE TITLE
floating window snapping doesn't feel quite right.

### ISSUE THREAD

**Issue by lex148** [leftwm/leftwm#28] opened 2019-04-27 12:19 UTC
Window snapping is great, but it doesn't feel quite right.

its hard to size/move a window that is near a snap edge.
play with other snapping windows and see how it can be better

**Comment by hertg** [comment] 2021-10-11 19:55
The issue #486 seems to be a duplicate of this one.
I'm closing this one here, because the other one got more comments :)

**Closed by hertg** 2021-10-11 19:55 UTC
