### ISSUE TITLE
LeftWM - AUR ==> ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by v3ss0n** [leftwm/leftwm#1090] opened 2023-06-17 12:08 UTC
### Describe the bug

When installed from repo, to test leftfm , it is having checksum error. on installation.

### Relevant log output (optional)

```text
==> Retrieving sources...
  -> Downloading leftwm-0.4.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9732k  100 9732k    0     0  2533k      0  0:00:03  0:00:03 --:--:-- 3466k
==> Validating source files with sha256sums...
    leftwm-0.4.2.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/nozander/.cache/yay/leftwm 
         context: exit status 1 
         

:: (1/1) Parsing SRCINFO: leftwm
==> Making package: leftwm 0.4.2-1 (Sat 17 Jun 2023 05:49:05 PM +0630)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found leftwm-0.4.2.tar.gz
==> Validating source files with sha256sums...
    leftwm-0.4.2.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: leftwm-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
leftwm - exit status 1
```
```


### OS / Distro

Linux noz-precision7730 6.2.16-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:09:09 UTC 2023 x86_64 GNU/Linux

### Additional System Information (optional)

_No response_

### LeftWM Check

```text
Linux noz-precision7730 6.2.16-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:09:09 UTC 2023 x86_64 GNU/Linux
```

**Comment by Eskaan** [comment] 2023-06-17 12:53
Which AUR package did you use? There are three of them.

**Comment by VuiMuich** [comment] 2023-06-17 12:57
There was the wrong sha checksum in `leftwm-0.4.2-1`. Please try again with `leftwm-0.4.2-2`, there was a positive report that this fixed the issue on discord.

Thanks for reporting in, though.

**Comment by v3ss0n** [comment] 2023-06-18 06:29
thanks , i am enjoying leftwm , i started it yesterday and now my system is quite  powerful now. Long ago i gave up on i3wm and xmonad , and i have been using KDE only for 6 + years , but even with Bismuth ( unmaintained now) and latest KDE tiled layout support , i am feeling lacking alot , and using mouse a lot. Now I am almost mouse free. 

After 1 day of configuration Leftwm is definately best tiling wm for x11! All sane defaults. really good layouts , scratchpad is wonderful! , themes also! 

Thanks a lot and keep it up leftwm deserves a lot more adoption.Sadly /r/unixporn is now private and cannot show off there.

**Comment by VuiMuich** [comment] 2023-06-19 05:28
Closing since fix is confirmed.

Thanks for the praise @v3ss0n!

**Closed** 2023-06-19 05:27 UTC
Labels: bug
