### ISSUE TITLE
Gentoo package depends on dev-lang/rust instead of virtual/rust. I would like to use rust-bin.

### ISSUE THREAD

**Issue by peter-winter** [leftwm/leftwm#957] opened 2022-11-17 07:06 UTC
### Describe the enhancement

DEPEND="
	x11-libs/libXinerama:0=
	x11-apps/xrandr:0=
	x11-base/xorg-server:0=
	>=dev-lang/rust-1.56.0   <---- here
"

### How important is this enhancement to you?

My workflow is impaired without it

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

**Comment by Eskaan** [comment] 2022-11-17 08:13
You will have to write the ebuild author, he is not on the team. I recommend you look at this ebuild: https://gitweb.gentoo.org/repo/proj/guru.git/tree/x11-wm/leftwm/leftwm-0.4.0.ebuild

**Comment by VuiMuich** [comment] 2022-11-17 10:11
As this is almost a duplicate of #954 and as Eskaan said the Gentoo maintainer seems not to be actively following our repo, I'll close this.

**Closed by VuiMuich** 2022-11-17 10:11 UTC
