### ISSUE TITLE
Newly opened floating windows with specific dimensions do not get sized properly

### ISSUE THREAD

**Issue by dementive** [leftwm/leftwm#1118] opened 2023-08-11 17:04 UTC
### Describe the bug

Some floating windows are sized improperly when they are opened, it seems to be only floating windows that have set sizes in the application that don't always get sized correctly.

Here is a screenshot of an example of the GIMP dds plugin popup that shows up when you open a dds file.
![gimp_dds_example](https://github.com/leftwm/leftwm/assets/87823030/60afbfbb-b55b-4f5c-881d-4da970a4bb14)

### Expected behavior (optional)

With all other window managers I've used this dds popup window would be minimized and to the smallest size it would scale the window nicely. But with leftwm the window doesn't minimize automatically like I would expect it to and there isn't a window_rules option to automatically set the dimensions of a newly spawned window so I don't see a way around it other than manually resizing the window every time it is opened.

Here is a screenshot of the expected behavior, this is using qtile on the exact same machine.
![gimp_expected_behavior](https://github.com/leftwm/leftwm/assets/87823030/ee39017d-8f79-4fb3-a65e-fe9cd0182287)

### Steps to reproduce (optional)

1. Download gimp 2.10
2. Find a dds file and open it with gimp
3. See the difference in behavior between the newly spawned leftwm floating windows and other window manager floating windows.

### OS / Distro

Arch and Garuda

### LeftWM Check

```text
:: LeftWM version: 0.4.2
:: LeftWM git hash: unknown
:: Enabled features:  journald-log lefthk
:: Checking feature dependencies . . .
    -> journald-log OK
    -> lefthk OK
:: Checking for leftwm binaries . . .
    -> Binaries OK 
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK
```

**Comment by Silicasandwhich** [comment] 2023-11-04 05:49
ive created a preliminary pull request with a fix that appears to work. it only affects windows on spawn, so windows that are made floating during their use shouldn't be erratically resized because they have a program-defined size. im going to run this branch for a little while to make sure it doesn't have any unforeseen consequences, feel free to do the same.

also, i have noticed that the text boxes in godot undergo a similar behavior, and that said behavior is not fixed by what i have implemented. I am considering looking into that to determine where the issue lies once the commit has been confirmed to not have any negative side effects.

**Closed** 2023-11-05 18:41 UTC
Labels: bug, regression
