### ISSUE TITLE
Scratchpads broken

### ISSUE THREAD

**Issue by FlyingPotato-131** [leftwm/leftwm#812] opened 2022-08-04 15:50 UTC
after an update when opening a scratchpad it always opens at 0,0 with the wrong size even though the size and position are specified.

**To Reproduce**
open a scratchpad with a specified size and position

**Expected behavior**
the scratchpad opens correctly

**Environment:**
Arch Linux
leftwm-check outputs that all is fine

**Comment by VuiMuich** [comment] 2022-08-04 21:58
🤔 this might be some regression introduced by #804. 
@jmattheis could you please check if your code overrides the scratchpad config?
I guess I may have missed this, due to the `SoftReload` persistence of the improved `xywh` behavior.

**Comment by jmattheis** [comment] 2022-08-06 12:36
If the scratchpad has WindowType::Normal, then it should probably be `if is_scatchpad() { ... } else if window.r#type == WindowType::Normal` in here, otherwise the xywh will be overriden with set_relative_floating.

https://github.com/leftwm/leftwm/blob/fc5d1047ad4a8fb7c85d8300dbdaa2b913ea0673/leftwm-core/src/handlers/window_handler.rs#L249-L272

**Comment by AethanFoot** [comment] 2022-08-06 13:00
Can u check if it happens on my refactor branch?

**Comment by justAlex0** [comment] 2022-08-06 18:27
That's not just scratchpad. This bug relates to all new non-tiling windows that appears (such as confirmation dialogs).

**Comment by hertg** [comment] 2022-08-15 18:25
> That's not just scratchpad. This bug relates to all new non-tiling windows that appears (such as confirmation dialogs), they all spawn at 0,0

I can confirm that this affects all floating windows, not just scratchpads

> Can u check if it happens on my refactor branch?

I can also confirm that PR #807 fixes this issue :tada:

**Comment by stevensonmt** [comment] 2022-08-17 18:04
I think I'm having the same issue, but my scratchpad spawns centered on the screen, not at 0,0. Config settings for position and dimensions are ignored.

**Comment by justAlex0** [comment] 2022-08-26 19:32
After #807 the scratchpad behaves as it expected by the config. But the issue still affects all floating windows.

**Comment by VuiMuich** [comment] 2022-09-02 14:04
closing this as the issue for floating windows has been reported in #824 now as well.

**Closed by VuiMuich** 2022-09-02 14:04 UTC
