### ISSUE TITLE
Conky: interesting issue.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [leftwm/leftwm#341] opened 2021-05-17 23:00 UTC
Hello,

I have been using this configuration for years, but when I start Conky on LeftWM it draw over every window started after it.

After several tweaks I discovered if I switch `own_window_argb_visual  = true,`  (enable true transparency) it works as expected; however, I don't use a composite and Conky have a black background .

Are you aware of anyway to make it work without enabling true transparency?

Thank you!

```
conky.config = {

    alignment      = 'top_right',
    background      = false,
    double_buffer       = true,

    own_window      = true,
    own_window_class    = 'conky',
    own_window_type     = 'override',
    own_window_transparent  = true,
    own_window_argb_visual  = false,

    draw_borders        = false,
    draw_graph_borders  = false,
    draw_outline        = true,
    draw_shades         = true,

    default_color       = '#f2f4f8',
    default_shade_color     = '#f2f4f8',
    default_outline_color   = '#000000',
    default_shade_color = '#f2f4f8',

    font            = 'Ohsnapu:size=8',
    use_xft         = true,
    xftalpha        = 100,

    uppercase       = false,
    format_human_readable   = true,
    short_units     = true,

    gap_x           = 7,
    gap_y           = 30,
    minimum_height      = 5,
    minimum_width       = 237,
    border_width        = 2,

    use_spacer      = 'left',

    no_buffers      = true,
    out_to_console      = false,
    out_to_stderr       = false,
    extra_newline       = false,

    cpu_avg_samples     = 2,
    net_avg_samples     = 2,
    diskio_avg_samples  = 2,
    update_interval     = 2.0,
    total_run_times     = 0

}
```

**Comment by AethanFoot** [comment] 2021-05-18 06:19
Try some of these options which allows my conky to work.
```
own_window_type = 'dock',	
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
```
Thanks.

**Comment by rigoletto-freebsd** [comment] 2021-05-18 18:49
Unfortunately not, with this configuration Conky don't show up at all! :-)

**Comment by AethanFoot** [comment] 2021-05-18 19:05
Heres my conky (haven't updated it in a while):
```
conky.config = {
	background = true,
	use_xft = true,
	font = 'MesloLGS NF:style=Bold:pixelsize=13',
	xftalpha = 0.5,
	update_interval = 1,
	total_run_times = 0,
	own_window = true,
	own_window_type = 'dock',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_argb_visual = false,
    --own_window_argb_value = 230,
    own_window_transparent = true,
    --own_window_colour = '#2d2d2d',
    double_buffer = true,
	minimum_width = 350, minimum_height = 5,
	maximum_width = 350,
	draw_shades = false,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = false,
	default_color = '#e6e6e6',
	default_shade_color = 'red',
	default_outline_color = 'green',
	alignment = 'top_right',
    --ximerama_head = 3,
	gap_x = 1934,
	gap_y = 48,
	no_buffers = true,
	uppercase = false,
	cpu_avg_samples = 2,
    override_utf8_locale = false,
};

conky.text = [[
System Info ${hr 2}

${color #bd93f9}${uid_name 1000}$color - $sysname $kernel
${color #bd93f9}Uptime:$color $uptime ${color lightgrey}${color #bd93f9}
Load:$color $loadavg${color lightgrey}

${color #bd93f9}CPU: ${color lightgrey}${execi 10000000 lscpu | grep 'Model name' | sed -r 's/Model name:\s{1,}(.*) @ .*z\s*/\1/g' | sed -e 's/CPU//'}
Core 1: ${cpubar cpu1 6,150}$alignr ${cpu cpu1}%  ${freq_g 1}GHz
Core 2: ${cpubar cpu2 6,150}$alignr ${cpu cpu2}%  ${freq_g 2}GHz
Core 3: ${cpubar cpu3 6,150}$alignr ${cpu cpu3}%  ${freq_g 3}GHz
Core 4: ${cpubar cpu4 6,150}$alignr ${cpu cpu4}%  ${freq_g 4}GHz
Core 5: ${cpubar cpu5 6,150}$alignr ${cpu cpu5}%  ${freq_g 5}GHz
Core 6: ${cpubar cpu6 6,150}$alignr ${cpu cpu6}%  ${freq_g 6}GHz
Core 7: ${cpubar cpu7 6,150}$alignr ${cpu cpu7}%  ${freq_g 7}GHz
Core 8: ${cpubar cpu8 6,150}$alignr ${cpu cpu8}%  ${freq_g 8}GHz

CPU utilisation$alignr ${cpu cpu0}%
${cpubar cpu0}
${cpugraph ff79c6 ffb2f0}
${color #bd93f9}GPU: ${color lightgrey}${execi 10000000 nvidia-smi --query-gpu=gpu_name --format=csv,noheader} - ${execi 10000000 nvidia-smi --query-gpu=driver_version --format=csv,noheader} 
Frequency: ${nvidia gpufreq}Mhz Tempature: ${nvidia temp}C

GPU utilisation$alignr ${execp nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader | sed -e 's/ %//'}%
${execbar nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader | sed -e 's/ %//'}

Memory ${hr 2}

MEM $alignc $mem / $memmax $alignr $memperc%
$membar

SWAP $alignc $swap / $swapmax $alignr $swapperc%
$swapbar

Top Processes ${hr 2}
$alignr $processes processes

NAME          $alignr PID    CPU    MEM
${top name 1} $alignr ${top pid 1} ${top cpu 1} ${top mem 1}
${top name 2} $alignr ${top pid 2} ${top cpu 2} ${top mem 2}
${top name 3} $alignr ${top pid 3} ${top cpu 3} ${top mem 3}
${top name 4} $alignr ${top pid 4} ${top cpu 4} ${top mem 4}
${top name 5} $alignr ${top pid 5} ${top cpu 5} ${top mem 5}

Network ${hr 2}

Down:    ${downspeed enp5s0}
${downspeedgraph enp5s0 ff79c6 ffb2f0}
Up:          ${upspeed enp5s0}
${upspeedgraph enp5s0 ff79c6 ffb2f0}
]];
```
own_window_argb_visual doesn't seem to make a difference for me.

**Comment by rigoletto-freebsd** [comment] 2021-05-18 19:32
Didn't work either. Conky not showing at all, and I'm thinking this is platform specific.

I will try to find out what is going on, and if I find I report later. For now I would close this issue.

Thank you.

**Comment by stevensonmt** [comment] 2021-05-19 01:54
I am on Manjaro Linux and have the same issue except that I already had `own_window_argb_visual = true` set. Changing window type to dock does not help.

**Comment by VuiMuich** [comment] 2021-05-19 05:09
I had an interesting conky misbehaviour my self, when I screwed up `theme.toml` while testing #329.
I forgot to switch from the config stale where `gutters` where configured as a singe line option to the final style like this
```toml
[[gutter]]
side = "Top"
value = 0
```
This led to `leftwm` using the internal default theme and seemingly `conky` din't like this and spawned all it's windows `floating`, even though the `theme.toml` was fixed.
After a reboot for a full system update `conky` is back to normal.

So I guess you could try to explicitly add a `gutter` (like the above which doesn't actually do anything) to your `theme.toml` and do a `hard reload` of `leftwm`.

**Comment by VuiMuich** [comment] 2021-05-19 05:19
Uuuhm, never mind. The issue is still here for me, gonna triage this further, but my guess now it is somewhat related to `eww` having windows open..

**Comment by hertg** [comment] 2022-09-07 16:38
Not a user of conky... is this still an issue? Can somebody using conky test this and maybe suggest a new issue title that better describes the problem?

**Comment by VuiMuich** [comment] 2022-09-08 08:53
Haven't been using `conky` in a long time either.
I'll see if I can test this in the next days.

**Comment by stevensonmt** [comment] 2022-09-08 18:17
I quit using conky in part because of this issu.

**Comment by VuiMuich** [comment] 2022-09-09 18:09
So I freshly installed conky and what seems to work right now is those settings (not using any compositor):
```
conky.config = {
	alignment = 'bottom_right',
	background = true,
	color2 = 'e2b714',
	cpu_avg_samples = 2,
	default_color = 'dcd8cf',
	double_buffer = true,
	font = 'Hasklug Nerd Font:size=14',
	draw_shades = false,
	gap_x = 25,
	gap_y = 13,
	minimum_width = 300,
	no_buffers = true,
	own_window = true,
	own_window_type = 'panel',
	own_window_transparent = true,
	own_window_argb_visual = false,
	update_interval = 1.0,
	use_xft = true,
}
conky.text = [[
${voffset 8}$color2${font Hasklug Nerd Font:size=16}${time %A}$font\
${voffset -8}$alignr$color${font Hasklug Nerd Font:size=38}${time %e}$font
$color${voffset -30}$color${font Hasklug Nerd Font:size=18}${time %b}$font\
${voffset -3} $color${font Hasklug Nerd Font:size=20}${time %Y}$font$color2$hr
#
${voffset 20}${goto 40}${color}CPU${font Hasklug Nerd Font:bold:size=8}$alignr$cpu%
${voffset 5}${goto 40}$font$color2${top name 1}$alignr$color${top cpu 1}%
${goto 40}$color2${top name 2}$alignr$color${top cpu 2}%
${goto 40}$color2${top name 3}$alignr$color${top cpu 3}%
${goto 40}$color2${top name 4}$alignr$color${top cpu 4}%
# ${goto 40}$color2${top name 5}$alignr$color${top cpu 5}%
#
${voffset 10}${goto 40}${color}RAM${font Hasklug Nerd Font:bold:size=8}$alignr$mem$font
${goto 40}${voffset 5}$color2${top_mem name 1}$alignr$color${top_mem mem_res 1}
${goto 40}$color2${top_mem name 2}$alignr$color${top_mem mem_res 2}
${goto 40}$color2${top_mem name 3}$alignr$color${top_mem mem_res 3}
${goto 40}$color2${top_mem name 4}$alignr$color${top_mem mem_res 4}
# ${goto 40}$color2${top_mem name 5}$alignr$color${top_mem mem_res 5}
#
${voffset 10}${goto 40}${color}Swap${font Hasklug Nerd Font:bold:size=8}$alignr${swap}/ ${swapfree}
${voffset 15}$font$alignr${execi 10000 awk -F= '/TION/ {print $2}' /etc/lsb-release |sed 's/"//g'} \
${execi 10000 awk -F= '/EASE=/ {printf $2" "} /NAME/ {print $2}' /etc/lsb-release}
${voffset 10}${color2}${alignr}${execi 1200 whoami}@${nodename}
${alignr}${color2}${font Hasklug Nerd Font:size=8}uptime: ${color}${uptime_short}
${voffset 5}${color2}${font Hasklug Nerd Font:size=8}${alignr}kernel: ${color}${kernel}
]]
```
![2022-09-09-195611_487x638_scrot](https://user-images.githubusercontent.com/4779365/189414557-e39b92a6-9193-4f3b-adcf-1eca34777522.png)
*ignore the last line of the screenshot, that was scrot messing things up*

Whats interesting is that we get some decent xprop output for this scenario but in other cases we only get the `WM_CLASS(STRING)` and nothing else:
```
~ >>> xprop
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 545, 0, 0, 0, 0, 0, 0, 2229, 2540
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 545
_NET_WM_DESKTOP(CARDINAL) = 3
WM_STATE(WM_STATE):
		window state: Normal
		icon window: <field not available>
_NET_WM_STATE(ATOM) =
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
WM_PROTOCOLS(ATOM): protocols
WM_NAME(STRING) = "conky (manjobook)"
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLASS(STRING) = "conky", "conky"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Don't Care State.
WM_CLIENT_MACHINE(STRING) = "manjobook"
WM_COMMAND(STRING) = { "conky", "-c", "/home/vuimuich/.config/conky/conky_maia" }
```

I guess we close this, and when someone feels the need to pursue this further feel free to reopen

**Closed by VuiMuich** 2022-09-09 18:09 UTC
Labels: bug
